import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/marketing/legal-page";
import { AUTHOR_NAME, CONTACT_EMAIL, SITE_URL } from "@/lib/brand";

export const metadata: Metadata = {
  title: "Privacy",
  description: `How ${SITE_URL.replace("https://", "")} handles account and repository data.`,
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy">
      <p>Last updated: 4 September 2026. Operated by {AUTHOR_NAME}.</p>
      <p>
        aiprreviewer ({SITE_URL}) is an open-source portfolio product that posts
        AI-generated comments on GitHub pull requests you connect. This page
        explains what we store and why.
      </p>
      <h2>Account data</h2>
      <p>
        Sign-in uses GitHub OAuth. We store your GitHub name, email (or a
        GitHub-provided noreply address), avatar URL, and session tokens needed
        to keep you logged in.
      </p>
      <h2>Repository and review data</h2>
      <p>
        If you install the GitHub App, we receive pull request metadata, diffs,
        and related webhook events so the review job can run. Optional repo
        sync may index file snippets so comments can cite nearby code. Review
        text is generated by a third-party model provider and may be posted
        back to GitHub on your connected repositories.
      </p>
      <h2>Billing</h2>
      <p>
        Paid plans are processed by Stripe. We store subscription status and
        Stripe customer identifiers. We do not store full card numbers.
      </p>
      <h2>Processors</h2>
      <ul>
        <li>GitHub — authentication, webhooks, and posting reviews</li>
        <li>Neon — application database</li>
        <li>OpenRouter (and upstream model hosts) — generating review text</li>
        <li>Pinecone — optional embeddings for repo sync</li>
        <li>Inngest — background jobs</li>
        <li>Stripe — checkout and subscriptions</li>
      </ul>
      <h2>Contact</h2>
      <p>
        Questions or deletion requests:{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. Also see{" "}
        <Link href="/contact">Contact</Link>.
      </p>
    </LegalPage>
  );
}
