import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/marketing/legal-page";
import { AUTHOR_NAME, CONTACT_EMAIL, GITHUB_REPO_URL, SITE_URL } from "@/lib/brand";

export const metadata: Metadata = {
  title: "Terms",
  description: `Terms of use for ${SITE_URL.replace("https://", "")}.`,
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use">
      <p>Last updated: 4 September 2026. Operated by {AUTHOR_NAME}.</p>
      <p>
        aiprreviewer is a student portfolio / open-source tool. Source:{" "}
        <a href={GITHUB_REPO_URL} target="_blank" rel="noreferrer">
          {GITHUB_REPO_URL}
        </a>
        . By using the site you agree to these terms.
      </p>
      <h2>The service</h2>
      <p>
        The product posts automated comments on GitHub pull requests after you
        sign in and install the GitHub App. Output is generated by language
        models and can be wrong, incomplete, or unsafe to follow without human
        review. You remain responsible for code you merge.
      </p>
      <h2>No warranty</h2>
      <p>
        The service is provided “as is”, without uptime, accuracy, or support
        guarantees. It may change or stop without notice.
      </p>
      <h2>Acceptable use</h2>
      <p>
        Do not use the service to attack systems, scrape in violation of GitHub
        or third-party terms, or submit content you are not allowed to process.
        We may disable accounts that abuse the GitHub App or API limits.
      </p>
      <h2>Contact</h2>
      <p>
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> ·{" "}
        <Link href="/privacy">Privacy</Link> · <Link href="/contact">Contact</Link>
      </p>
    </LegalPage>
  );
}
